language: python

# the python version(s) that will be used for testing
python:
  - "3.6"

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest